[package]
name = "test-wasm-macro"
version = "0.1.0"
edition = "2021"

[lib]
name = "test_wasm_macro"
proc-macro = true

[dependencies]
heck = "0.4.1"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = [ "full" ]}
wit-parser = "0.201.0"
wit-component = { workspace = true }
